/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Birds } from "./Birds";
export * as factories from "./factories";
export { Birds__factory } from "./factories/Birds__factory";
