/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Birds__factory } from "./Birds__factory";
export { TestContract__factory } from "./TestContract__factory";
