import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import ConnectButton from "../components/ConnectButton";
import BirdsList from "../components/BirdsList";
import EventsList from "../components/EventsList";
import useTestContract from "../contracts/useTestContract";

const Home: NextPage = () => {
  const { events } = useTestContract();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.connect}>
          <ConnectButton />
        </div>
        <h1 className={styles.title}>Welcome to Birds NFTs</h1>
        <div>
          <EventsList events={events} />
          <BirdsList />
        </div>
      </main>
    </div>
  );
};

export default Home;
